text:
  p1:
  - kind: heading
    level: 1
    text: 仕事で使えるComposer
  - kind: heading
    level: 2
    text: 無修正版
  - kind: para
    text: ピクシブ株式会社うさみけんた @tadsan
  - kind: para
    text: PHPカンファレンス北海道2016
  p2:
  - kind: heading
    level: 1
    text: お前誰よ
  - kind: list
    items:
    - うさみけんた (@tadsan) / Zonu.EXE
    - GitHub/Packagistでは id:zonuexe
    - プログラミング言語と日本語が好き
    - 北海道工業大学(当時) 電子計算機研究部出身
    - 2012年頃までRuby札幌とかPython札幌で活動
    - 2012年11月に初めての就職（現職）
    - PHPは現職に所属してからまじめに取り組み
  p3:
  - kind: heading
    level: 1
    text: おしながき
  - kind: list
    items:
    - Composerの基礎／導入
    - ナウいPHPライブラリの探しかた
    - Composerとデプロイについて
    - そのほかもろもろのこと
  p4:
  - kind: para
    text: Version 1.0.0 was released on April 5, 2016
  p5:
  - kind: para
    text: 'Composer #とは'
  p6:
  - kind: heading
    level: 1
    text: Composerって何よ
  - kind: list
    items:
    - 依存関係管理ツール (Dependency manager)
    - YumやAPTはシステムにライブラリを導入する
    - Composerは、特定のプロジェクト単位に対して
  - kind: para
    text: 閉じて依存性を管理する
  - kind: list
    items:
    - npm(Node.js)やBundler(Ruby)に影響を受けた
    - グローバル(特定のプロジェクトに依存しない)
  - kind: para
    text: インストールも可能ではある
  p7:
  - kind: heading
    level: 1
    text: Get Composer!
  - kind: list
    items:
    - 2016年4月5日(今月) 正式版1.0.0リリース！
    - https://getcomposer.org/download/
    - PHAR形式で配布されてるので、
  - kind: para
    text: PHP(5.3.2+)がある環境ならどこでも動作する
  - kind: list
    items:
    - Linux/OS XのみならずWindowsもサポートしてる
    - Packagist, GitHub, PEARなどと連携可能
  p8:
  - kind: heading
    level: 1
    text: Composer VS pear
  - kind: list
    items:
    - pearはPHP標準のパッケージ管理コマンド
    - 機能の豊富さ、利用できるパッケージの数、
  - kind: para
    text: 新鮮さのような違いはもちろんある。
  - kind: list
    items:
    - それ以上に、PHPプロジェクトと同時にデプロイ可
  - kind: para
    text: 能になったことが非常に重要
  - kind: list
    items:
    - ライブラリを導入する権限がインフラ／サーバー管
  - kind: para
    text: 理者からアプリエンジニアの手に落ちてきた（身分制度の変革）
  p9:
  - kind: heading
    level: 1
    text: Composerは何ではないか
  - kind: list
    items:
    - PHPのC extensionはインストールできない
    - インストール済か確認することはできる
    - 従来通りPECLなどを利用することになる
  p10:
  - kind: para
    text: Composerの基礎
  p11:
  - kind: heading
    level: 1
    text: composer.json
  - kind: list
    items:
    - プロジェクトの情報を記述するファイル
    - 一般的にはプロジェクトのルートに置く
    - 依存情報やオートローディング設定など
    - パッケージ名はvendor/packageの形式
    - vendorは組織名やアカウント名をつける
    - Javaのように厳密に決まってるわけじゃない
  p12:
  - kind: heading
    level: 1
    text: ライブラリの依存を記述
  - kind: list
    items:
    - requireに依存するパッケージ+バージョンを記述
  - kind: para
    text: '{"require": {"filp/whoops": "~2.1.0"},"require-dev": {"phpunit/phpunit":
      "^4.8"}}'
  - kind: list
    items:
    - composer require --dev "phpunit/phpunit:4.8"
  p13:
  - kind: heading
    level: 1
    text: バージョン記法 (一部)
  - kind: list
    items:
    - '"*": 全てのバージョンを受け入れる'
    - '"1.2.3"：バージョンタグ固定'
    - '"~1.2.3": バージョンタグ固定(マイナー更新する)'
    - '"dev-xxxxx": ブランチxxxxxを指定'
    - dev-master#82115e5e37fa046464cのようにブラ
  - kind: para
    text: ンチとコミットIDを指定できる(しないと危険)
  p14:
  - kind: heading
    level: 1
    text: composer.lock
  - kind: list
    items:
    - 依存パッケージのバージョンを固定するファイル
    - composer.jsonでは範囲や複数指定が可能
    - 固定することで、意図しないバージョンが
  - kind: para
    text: 勝手にインストールされることを防ぐ
  - kind: list
    items:
    - 自動生成されるので手動編集しない方が良い
  p15:
  - kind: heading
    level: 1
    text: composer.lockの管理
  - kind: list
    items:
    - composer update vendor/package で更新
    - 自動生成されるcomposer.lockをGitなどの
  - kind: para
    text: バージョン管理の対象にするべきかは場合による
  - kind: list
    items:
    - アプリケーションでは管理することが多い
    - ライブラリは基本的に管理しない
    - 管理しない場合は .gitignore に設定しておく
  p16:
  - kind: heading
    level: 1
    text: Composerを使う
  - kind: list
    items:
    - 依存ライブラリはvendor/ディレクトリに入る
    - プロジェクトの .gitignore で除外しておく
    - Composerに依存するPHPには以下の一行を書く
  - kind: para
    text: require __DIR__ . '/vendor/autoload.php';
  - kind: list
    items:
    - 何度も書く必要はなく、一度だけ読み込めばいい
    - Composerでインストールされたライブラリは、
  - kind: para
    text: include_onceする必要がない
  p17:
  - kind: heading
    level: 1
    text: オートローディング
  - kind: list
    items:
    - PHPerをinclude_onceから解き放つ福音
  - kind: para
    text: '{"autoload": {"classmap": ["./src"]},"autoload-dev": {"classmap": ["./tests"]}}'
  - kind: list
    items:
    - 詳しくはWEB+DB Vol. 81に書きました(宣伝)
  p18:
  - kind: heading
    level: 1
    text: サブコマンド (一部)
  - kind: list
    items:
    - 'composer install: 必要なパッケージをインストール'
    - 'composer list: 機能一覧を出力'
    - 'composer self-update: composer.pharを更新'
    - 'composer search: パッケージ検索'
    - 'composer validate: composer.jsonのチェック'
    - 'composer create-project:'
  - kind: para
    text: フレームワークの雛形からプロジェクトを新規作成
  p19:
  - kind: para
    text: Composerを導入する
  p20:
  - kind: heading
    level: 1
    text: Composerの配置を考える
  - kind: list
    items:
    - 公式サイトのスクリプトでは、ダウンロードまで
  - kind: para
    text: しかしてくれない (Windowsにはしてくれる)
  - kind: list
    items:
    - 仕事の性質に配置方法には一考の余地がある
    - サーバーごと
    - ユーザーごと
    - プロジェクトごと
  p21:
  - kind: heading
    level: 1
    text: サーバーごとの場合
  - kind: list
    items:
    - プロジェクトメンバーが共有の開発サーバーに
  - kind: para
    text: ログインして作業する場合にとれる方法
  - kind: list
    items:
    - /usr/local/bin/composer.phar など
    - 良い点：Composerのバージョン差異がなくなる
    - 悪い点：サーバー管理者が更新しなきゃいけない
  - kind: para
    text: サーバー多いとめんどくさい
  p22:
  - kind: heading
    level: 1
    text: ユーザーごとの場合
  - kind: list
    items:
    - プロジェクトメンバーが自分のPCで開発する
  - kind: para
    text: 場合とか、ライブラリをいろいろ作る場合とか
  - kind: list
    items:
    - $HOME/bin/composer.phar など (好みによる)
    - 良い点：メンテナンスするライブラリの数が
  - kind: para
    text: 多い場合は管理が楽
  - kind: list
    items:
    - 悪い点：バージョンを同期させるのがめんどう
  - kind: para
    text: PATH通したりsudoさせたり説明めんどう
  p23:
  - kind: heading
    level: 1
    text: プロジェクトごとの場合
  - kind: list
    items:
    - 大規模な開発チームで一つのリポジトリを
  - kind: para
    text: 継続的に開発していく場合とか
  - kind: list
    items:
    - プロジェクト内の /composer.phar など
    - 良い点：メンバー間のバージョン差異はなくせる
    - 悪い点：プロジェクト数が多いと運用が面倒
  - kind: para
    text: ディスクスペースの浪費 (1.6MB程度)
  p24:
  - kind: heading
    level: 1
    text: 結局どれがいいの？
  - kind: list
    items:
    - PHPに詳しくないひとのことを考えると、
  - kind: para
    text: プロジェクトごとにcomposer.pharを置くのが一番楽じゃないかと思う
  - kind: list
    items:
    - セットアップスクリプトでダウンロードさせても
  - kind: para
    text: いいけど、pixivでは git commit しちゃってる
  - kind: list
    items:
    - 毎月更新するとして1.6MBのディスクスペースの
  - kind: para
    text: 浪費は、運用の手間を考えれば甘受できるレベル
  p25:
  - kind: heading
    level: 1
    text: xdebugとComposer
  - kind: list
    items:
    - xdebugが有効な環境でComposer使うと怒られる
  - kind: para
    text: You are running composer with xdebug enabled. This has a major impact on
      runtime performance. See https://getcomposer.org/xdebug
  - kind: list
    items:
    - xdebugは開発中は有用なので外したくない
    - 実際遅くなるのでシェルスクリプトを噛ませたい
    - composer.phar を php -n で起動できればいい
    - php.iniを無効化する＝拡張が有効にならない
  p26:
  - kind: heading
    level: 1
    text: Composerのラッパー
  - kind: list
    items:
    - プロジェクトローカルに置く場合…
    - composer.pharを.composer.pharにリネーム
    - かわりに ./composer を利用
    - chmod +x ./composer で実行権限を付与
    - ファイルの中身は以下の二行
  - kind: para
    text: '#!/bin/sh php -n $(dirname $0)/.composer.phar "$@"'
  p27:
  - kind: heading
    level: 1
    text: 環境変数
  - kind: list
    items:
    - Composerに必要なファイルはCOMPOSER_HOME
  - kind: para
    text: 環境変数のディレクトリにインストール
  - kind: list
    items:
    - デフォルトでユーザディレクトリにインストール
  - kind: para
    text: (Linux/OS X) $HOME/.composer(Windows)
  - kind: para
    text: '%APPDATA%¥Composer'
  - kind: list
    items:
    - システムの設定を工夫すれば共有ディレクトリに
  - kind: para
    text: インストールすることも可能ではある
  - kind: para
    text: (やったことないけど)
  p28:
  - kind: heading
    level: 1
    text: Composerを導入
  - kind: list
    items:
    - UNIX系OSでユーザごとにインストールするとき
  - kind: heading
    level: 2
    text: $HOME/local/bin/composer に配置しておくと便利
  - kind: heading
    level: 2
    text: (.bash_profileや.zshenvなどでPATHを通す)
  - kind: para
    text: '# .bash_profile/.bashrc PATH=$HOME/.composer/vendor/bin:$HOME/local/bin:$PATH#
      .zshenv/.zshrc path=(~/.composer/vendor/bin(N-/)~/local/bin(N-/)$path)'
  p29:
  - kind: para
    text: PHPのライブラリを探す
  p30:
  - kind: heading
    level: 1
    text: Packagist
  - kind: para
    text: The PHP Package Repository
  p31:
  - kind: heading
    level: 1
    text: Packagistって何だ
  - kind: list
    items:
    - https://packagist.org/
    - PHPのパッケージリポジトリ
    - 2012年から4月から活動してる (４周年！)
    - 現在92,973パッケージ登録されてる
    - ちなみにPEARのパッケージ数は602
  p32:
  - kind: para
    text: http://www.modulecounts.com/
  p33:
  - kind: heading
    level: 1
    text: Packagistの特徴
  - kind: list
    items:
    - GitHubなどのリポジトリと簡単に連携できる
    - API連携した状態なら、git tagをつけるだけで
  - kind: para
    text: かんたんに新しいバージョンをリリースできる
  - kind: list
    items:
    - 有名なライブラリ／フレームワークは登録済み
    - 歴史的にフレームワークはzipファイルで公開
  - kind: para
    text: されてきたが、現在はComposerでもインストールできる
  p34:
  - kind: heading
    level: 1
    text: ライブラリを探す
  - kind: list
    items:
    - とりあえず awesome-php に載ってるものを
  - kind: para
    text: 触ってみる
  - kind: list
    items:
    - 各ジャンルの手堅いライブラリの一覧
    - たいていのコンポーネントは大手が作ってる
    - SymfonyとかHoaProjectとか
    - Twitterの@call_user_funcをフォローすると
  - kind: para
    text: 新着のライブラリがいっぱい流れてくる
  p35:
  - kind: para
    text: Composerとデプロイ
  p36:
  - kind: heading
    level: 1
    text: デプロイ、どうしてますか？
  - kind: list
    items:
    - 稼働中のサーバーに高速にコードを配置したい
    - rsyncなどで愚直にファイルを配置すると、
  - kind: para
    text: 最中のPHPファイルが書き変わっちゃって処理途中のユーザーリクエストがエラーで落ちる
  - kind: list
    items:
    - Composerにも自動生成ファイルがあるので、
  - kind: para
    text: デプロイを工夫しないと、やはり落ちることが
  p37:
  - kind: heading
    level: 1
    text: アトミックデプロイ
  - kind: list
    items:
    - エラーが出ないようにデプロイ途中の不完全な
  - kind: para
    text: 状態がユーザーの目に触れないよう工夫する
  - kind: list
    items:
    - 弊社事例(rsync+デプロイスクリプト手書き)は
  - kind: para
    text: WEB+DB PRESS vol. 84に載ってる
  - kind: list
    items:
    - 最近はDeployer http://deployer.org/ が
  - kind: para
    text: いい感じにアトミックデプロイしてくれるらしい(環境に合せて検証の必要あり)
  p38:
  - kind: para
    text: Satis - Package Repository Generator
  - kind: list
    items:
    - https://github.com/composer/satis
    - 要はプライベートなPackagistを自前運用できる
    - パッケージのアーカイブを保存できるので、
  - kind: para
    text: もしGitHubが不通になってしまってもデプロイできない事態を避けることができる
  - kind: list
    items:
    - デプロイ先のサーバーとネットワーク的に
  - kind: para
    text: 近いところにあればデプロイ時間の短縮になる
  p39:
  - kind: heading
    level: 1
    text: Satisの運用
  - kind: list
    items:
    - 必要なライブラリをsatis.jsonに列挙する
    - 記法はcomposer.jsonと同じ
    - '"~2.1.0"記法よりは">=2.1.0"が良い'
    - satis.jsonとビルドスクリプトを置いた
  - kind: para
    text: リポジトリを用意して、毎日定時とsatis.jsonが更新されたときに新鮮なパッケージを取得
  p40:
  - kind: heading
    level: 1
    text: Satisを使う場合のcomposer.json
  - kind: para
    text: '{"repositories": [{"packagist": false},{"type": "composer","url": "http://satis.pixiv.private/"}]}'
  p41:
  - kind: para
    text: パッケージ作りたい
  p42:
  - kind: heading
    level: 1
    text: 基本
  - kind: list
    items:
    - PackagistはGitHubでログインできるので、
  - kind: para
    text: GitHubに上げると非常に楽
  - kind: list
    items:
    - ブラウザで https://packagist.org を開いて
  - kind: para
    text: 説明通りに入力していくだけ
  - kind: list
    items:
    - 新しいバージョンのリリースは、
  - kind: para
    text: git tag 1.4.5 && git push --tags で完了
  p43:
  - kind: heading
    level: 1
    text: お作法
  - kind: list
    items:
    - Composerはオートローディングが基本なので、
  - kind: para
    text: 不必要なinclude_onceは書かない
  - kind: list
    items:
    - PSR-1, PSR-2, PSR-4 を読んでおけば、
  - kind: para
    text: だいたい綺麗なコードが書ける気がする
  - kind: list
    items:
    - PSR-1, PSR-2はインフィニットループさんに
  - kind: para
    text: よる日本語訳がWebにあります
  - kind: list
    items:
    - とりあえずnamespaceは付けといた方が良い
  p44:
  - kind: para
    text: Composerが遅い
  p45:
  - kind: heading
    level: 1
    text: Packagistは遠い
  - kind: list
    items:
    - GitHub/Packagistは日本から遠いところに
  - kind: para
    text: あるので、ネットワークコストが非常に高い
  - kind: list
    items:
    - これはSatisを置けば解決する
    - Satisを用意できない／用意するまでもない
  - kind: para
    text: ときは、Hirakuさんという方がミラーサイトhttps://packagist.jp/を用意してくれてるので、これを使える
  p46:
  - kind: heading
    level: 1
    text: Composerは遅い
  - kind: list
    items:
    - ComposerはPHPの互換性を重視してるので、
  - kind: para
    text: 最適な実装ではない
  - kind: list
    items:
    - Hirakuさんが並列ダウンロードできるようにした
    - composerを速くするプラグイン・prestissimoを作った
  - kind: para
    text: http://blog.tojiru.net/article/432944706.html
  - kind: list
    items:
    - GitHubで既に★1660個ついてる！
  p47:
  - kind: para
    text: グローバルにライブラリをインストール
  p48:
  - kind: heading
    level: 1
    text: どんなときにグローバル？
  - kind: list
    items:
    - 実際出番はあまりない
    - コマンドとしてインストールしたいライブラリ
    - いちいちプロジェクトを作るまでもない
  - kind: para
    text: 使い捨てコードから利用したいライブラリ
  - kind: list
    items:
    - グローバルインストールしても、
  - kind: para
    text: 勝手に読み込まれるようなことはない
  p49:
  - kind: heading
    level: 1
    text: PsySHはべんり
  - kind: list
    items:
    - composer global require psy/psysh
    - PHPの対話環境 (REPL)
    - RubyのIRB, Pryのようなもの
    - ただし実行中に関数やクラスの再定義は
  - kind: para
    text: できないので注意すること
  - kind: list
    items:
    - psysh.el もあるよ (宣伝／未完成)
size:
  max_width: 1024
  max_height: 768
links:
  p7:
  - url: https://getcomposer.org/download/
    title: Composer
  p25:
  - url: https://getcomposer.org/xdebug
    title: Troubleshooting - Composer
  p31:
  - url: https://packagist.org/
    title: Packagist
  p34:
  - url: https://github.com/ziadoz/awesome-php
    title: 'GitHub - ziadoz/awesome-php: A curated list of amazingly awesome PHP libraries,
      resources and shiny things.'
  - url: http://symfony.com
    title: Symfony, High Performance PHP Framework for Web Development
  - url: http://hoa-project.net/En/
    title: hoa-project.net
  - url: https://twitter.com/call_user_func
    title: twitter.com
  p37:
  - url: http://deployer.org/
    title: Deployer - The deployment tool for PHP | Deployer
  p38:
  - url: https://github.com/composer/satis
    title: 'GitHub - composer/satis: Simple static Composer repository generator -
      For a full private Composer repo use Private Packagist'
  p42:
  - url: https://packagist.org
    title: Packagist
  p45:
  - url: https://packagist.jp/
    title: Packagist.JP
  p46:
  - url: http://blog.tojiru.net/article/432944706.html
    title: 'composerを速くするプラグイン・prestissimoを作った: Architect Note'
