size:
  max_width: 1024
  max_height: 768
links:
  p7:
  - url: https://getcomposer.org/download/
    title: Composer
  p25:
  - url: https://getcomposer.org/xdebug
    title: Troubleshooting - Composer
  p31:
  - url: https://packagist.org/
    title: Packagist
  p34:
  - url: https://github.com/ziadoz/awesome-php
    title: 'GitHub - ziadoz/awesome-php: A curated list of amazingly awesome PHP libraries,
      resources and shiny things.'
  - url: http://symfony.com
    title: Symfony, High Performance PHP Framework for Web Development
  - url: http://hoa-project.net/En/
    title: hoa-project.net
  - url: https://twitter.com/call_user_func
    title: twitter.com
  p37:
  - url: http://deployer.org/
    title: Deployer - The deployment tool for PHP | Deployer
  p38:
  - url: https://github.com/composer/satis
    title: 'GitHub - composer/satis: Simple static Composer repository generator -
      For a full private Composer repo use Private Packagist'
  p42:
  - url: https://packagist.org
    title: Packagist
  p45:
  - url: https://packagist.jp/
    title: Packagist.JP
  p46:
  - url: http://blog.tojiru.net/article/432944706.html
    title: 'composerを速くするプラグイン・prestissimoを作った: Architect Note'
