text:
  p1:
  - kind: heading
    level: 1
    text: プログラミング環境としての
  - kind: para
    text: Introducing PHP as a Programming Environment
  - kind: para
    text: '2017-08-19 NEEC Kamata #opendevcon'
  - kind: para
    text: Open Developers Conference 2017 Tokyo
  p2:
  - kind: heading
    level: 1
    text: お前誰よ
  - kind: list
    items:
    - うさみけんた (@tadsan) / Zonu.EXE
    - 'GitHub/Packagistでは id: zonuexe'
    - ピクシブ株式会社でひたすらPHPやってる p(ixi)v
    - フレームワークなき道にフレームを作るおしごと
    - Qiitaに記事を書いたり変なコメントしてるよ
    - 最近やってること
    - 万難が排されつつあるのでPHP7 移行
    - えいやえいやとテスト書いたり直したりしてる
  p3:
  - kind: para
    text: 最初に
  - kind: para
    text: 覚えてほしいこと
  p4:
  - kind: para
    text: 現在の安定版は
  - kind: para
    text: 7.1系です
  p5:
  - kind: para
    text: 質問です
  p6:
  - kind: para
    text: あなたの想像する
  - kind: para
    text: PHPコードはどれ？
  p7:
  - kind: heading
    level: 1
    text: A
  - kind: para
    text: <!DOCTYPE html>
  - kind: para
    text: <html><head><title>Hello, PHP!</title></head>
  - kind: para
    text: <p>
  - kind: para
    text: '<?php if (date(''H'') < 19): ?>'
  - kind: para
    text: こんにちは
  - kind: para
    text: '<?php else: ?>'
  - kind: para
    text: こんばんは
  - kind: para
    text: <?php endif; ?>
  - kind: para
    text: </p>
  - kind: para
    text: <p>今は<?= htmlspecialchars(date('H')) ?>時です</p>
  p8:
  - kind: heading
    level: 1
    text: B
  - kind: para
    text: <?php require 'bootstrap.php';
  - kind: para
    text: $db = mysqli_connect();
  - kind: para
    text: $stmt = mysqli_prepare($db, 'SELECT * FROM books');
  - kind: para
    text: mysqli_stmt_execute($stmt);
  - kind: para
    text: print '<h1>本の一覧</h1>';
  - kind: para
    text: print '<ul>';
  - kind: para
    text: foreach ($stmt as $s) {
  - kind: para
    text: print '<li>'; print $s->name; print '</li>';
  - kind: para
    text: '}'
  - kind: para
    text: print '</ul>';
  p9:
  - kind: heading
    level: 1
    text: C
  - kind: para
    text: <?php
  - kind: para
    text: namespace Hoge\Http\Controller;
  - kind: para
    text: class BooksController extends BaseController {
  - kind: para
    text: public function index() {
  - kind: para
    text: $books = Books::getAll();
  - kind: para
    text: $this->render(compact("books"));
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  p10:
  - kind: para
    text: いろいろある
  p11:
  - kind: heading
    level: 1
    text: よくあるPHPのコード分類
  - kind: para
    text: 'A: HTMLの条件分岐と値の出力'
  - kind: para
    text: 'B: DBの内容をHTMLとして出力'
  - kind: para
    text: 'C: クラス定義だけ書かれたコード'
  p12:
  - kind: heading
    level: 1
    text: よくあるPHPのコード分類
  - kind: para
    text: 'A: HTMLの条件分岐と値の出力'
  - kind: para
    text: ↑ SSI的PHP
  - kind: para
    text: 'B: DBの内容をHTMLとして出力'
  - kind: para
    text: ↑ CGI的PHP
  - kind: para
    text: 'C: クラス定義だけ書かれたコード'
  - kind: para
    text: ↑ フレームワーク的PHP
  p13:
  - kind: para
    text: 割とどうとでも
  - kind: para
    text: 書けるのがPHP
  p14:
  - kind: heading
    level: 1
    text: PHPの実行手順のイメージ
  - kind: para
    text: コードを書く (or 既製コードを準備)
  - kind: para
    text: レンタルサーバーを借ります
  - kind: para
    text: (S)FTPで.phpファイルを転送します
  - kind: para
    text: デプロイ完了 ＼(^o^)／
  p15:
  - kind: para
    text: PHPで書くとURLに
  - kind: para
    text: .phpって付くのでは??
  p16:
  - kind: heading
    level: 1
    text: そんなことはない
  - kind: para
    text: (そんなこともある)
  p17:
  - kind: heading
    level: 2
    text: ディレクトリ配置のイメージ
  - kind: heading
    level: 1
    text: これをな
  - kind: para
    text: php-project/
  - kind: para
    text: ├── inc
  - kind: para
    text: │ └── bootstrap.php
  - kind: para
    text: └── public (ドキュメントルート)
  - kind: para
    text: ├── index.php
  - kind: para
    text: ├── login.php
  - kind: para
    text: ├── logout.php
  - kind: para
    text: └── terms.html
  p18:
  - kind: heading
    level: 2
    text: ディレクトリ配置のイメージ
  - kind: heading
    level: 1
    text: こうじゃ
  - kind: para
    text: php-project/
  - kind: para
    text: ├── inc
  - kind: para
    text: │ ├── bootstrap.php
  - kind: para
    text: │ └── routes.php
  - kind: para
    text: └── public (ドキュメントルート)
  - kind: para
    text: ├── .htaccess (Apacheの場合)
  - kind: para
    text: └── index.php
  p19:
  - kind: para
    text: このPHPを動かすに
  - kind: para
    text: はどうすればいいの
  p20:
  - kind: heading
    level: 1
    text: PHPの動作方法にはいろいろある
  - kind: para
    text: Server API (SAPI) と呼ばれる
  - kind: para
    text: コマンドライン (cli, cli-server)
  - kind: para
    text: Apache+mod_php (apache)
  - kind: para
    text: CGI (cgi-fcgi)
  - kind: para
    text: PHP-FPM (fpm-fcgi)
  p21:
  - kind: heading
    level: 1
    text: どこでPHPを動かせばいいか
  - kind: para
    text: 何も考えずにレンタルサーバ借りて、
  - kind: para
    text: ファイルを適当に転送すれば動く
  - kind: para
    text: HerokuとかPaaSでも簡単に動く
  - kind: para
    text: オンプレとかVPSとかでアプリケー
  - kind: para
    text: ションサーバーを実行する方法もある
  p22:
  - kind: para
    text: テストするだけなら
  - kind: para
    text: PHPだけあればok
  p23:
  - kind: para
    text: php -S
  - kind: para
    text: localhost:8989 index.php
  p24:
  - kind: para
    text: ビルトインサーバー
  - kind: para
    text: (php -S) PHP5.4以降
  - kind: para
    text: 開発用の簡易HTTP鯖
  p25:
  - kind: heading
    level: 1
    text: よくある.htaccess (Apache HTTPd)
  - kind: para
    text: '# ファイルがあったら、それを返す(.phpなら実行)'
  - kind: para
    text: '# 存在しなかったら、index.phpを実行'
  - kind: para
    text: RewriteCond %{REQUEST_FILENAME} !-f
  - kind: para
    text: RewriteRule ^ index.php [QSA,L]
  p26:
  - kind: heading
    level: 1
    text: 愚直な routes.php
  - kind: para
    text: <?php
  - kind: para
    text: $path = substr(explode('?', $_SERVER['REQUEST_URI'], 2)[0], 1);
  - kind: para
    text: $is_post = $_SERVER['REQUEST_METHOD'] === 'POST';
  - kind: para
    text: if ($is_get && $path === '/') {
  - kind: para
    text: show_index(); return;
  - kind: para
    text: '} elseif ($path === ''/login'') {'
  - kind: para
    text: '$is_post ? post_login() : show_login(); return;'
  - kind: para
    text: '}'
  - kind: para
    text: http_response_code(404);
  - kind: para
    text: echo "ないよー";
  p27:
  - kind: para
    text: これを毎回自分で書くのは
  - kind: para
    text: ちょっぴり大変なので、
  - kind: para
    text: フレームワークを利用する
  p28:
  - kind: para
    text: PHP
  - kind: para
    text: micro framework
  - kind: para
    text: Slim, Lumen など
  p29:
  - kind: para
    text: シンプルなルーティ
  - kind: para
    text: ングがしたかった
  - kind: para
    text: https://qiita.zonu.me/simple-routing
  p30:
  - kind: para
    text: そろそろ言語の話
  p31:
  - kind: para
    text: PHPには「protected属性」も「仮想メソッ
  - kind: para
    text: ド」もありますよ。情報学科の教官が「重
  - kind: para
    text: 要だ」っていうやつは何でもね。僕自身は、
  - kind: para
    text: こんなものどうでもいいと思ってますけど。
  - kind: para
    text: –Rasmus Lerdorf
  - kind: para
    text: 伝説のPHP作者「Rasmus Lerdorf」名言集を聞くと嫌PHP厨がファビョる
  - kind: para
    text: https://anond.hatelabo.jp/20100427231539 の訳を抜萃
  p32:
  - kind: para
    text: 実際ふつうの言語にある
  - kind: para
    text: 機能はだいたいある
  p33:
  - kind: para
    text: Linux, *BSD,
  - kind: para
    text: macOS, Windows
  p34:
  - kind: para
    text: RubyやPythonで書けること
  - kind: para
    text: は概ねできると思ってよい
  - kind: para
    text: (異常に苦手なことはある)
  p35:
  - kind: para
    text: Cっぽさ、Perlっぽさ、
  - kind: para
    text: そこはかとないJavaっぽさ
  - kind: para
    text: (結果としてどれでもない雑然とした感じ)
  p36:
  - kind: heading
    level: 1
    text: Cっぽいコード
  - kind: para
    text: <?php
  - kind: para
    text: $fp = fopen('input.txt', 'r');
  - kind: para
    text: $i = 0;
  - kind: para
    text: while (($line = fgets($fp, 4096)) !== false) {
  - kind: para
    text: 'printf("%d: %s", ++$i, $line);'
  - kind: para
    text: '}'
  p37:
  - kind: heading
    level: 1
    text: Perlっぽいコード
  - kind: para
    text: <?php
  - kind: para
    text: $con = mysqli_connect() or die(1);
  - kind: para
    text: '# ただし、現在は例外を利用すべき'
  - kind: para
    text: '# テストもしにくくなるので非推奨'
  p38:
  - kind: heading
    level: 1
    text: Javaっぽいコード
  - kind: para
    text: <?php
  - kind: para
    text: abstract class Foo {
  - kind: para
    text: abstract function sample($n);
  - kind: para
    text: '}'
  - kind: para
    text: final class Bar extends Foo implements Hoge {
  - kind: para
    text: public function sample($n) {
  - kind: para
    text: if (!is_numeric($n)) {
  - kind: para
    text: throw new InvalidArgumentException("errorMsg");
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  - kind: para
    text: $bar = new Bar(); $bar->sampleCode(128);
  p39:
  - kind: para
    text: PHPの
  - kind: para
    text: 基本構文
  p40:
  - kind: heading
    level: 1
    text: データ型・リテラル
  - kind: para
    text: <?php
  - kind: para
    text: // 全ての変数は $ から始まる
  - kind: para
    text: $string = 'string' . "value";
  - kind: para
    text: $array = [1, 2, 3];
  - kind: para
    text: $bool = true;
  - kind: para
    text: $int = 56789;
  - kind: para
    text: $float = 1.234;
  - kind: para
    text: $obj1 = new stdClass;
  - kind: para
    text: $obj2 = (object)["name" => "Miku", "age" => 16];
  p41:
  - kind: heading
    level: 1
    text: 関数定義
  - kind: para
    text: <?php
  - kind: para
    text: namespace zonuexe;
  - kind: para
    text: function triangle_area(float $h, float $b) :float {
  - kind: para
    text: return $h * $b / 2;
  - kind: para
    text: '}'
  - kind: para
    text: function triangle_area($h, $b) {
  - kind: para
    text: return $h * $b / 2;
  - kind: para
    text: '}'
  p42:
  - kind: heading
    level: 1
    text: 関数・クラス定義の注意
  - kind: para
    text: RubyやPythonでは関数(メソッド)を
  - kind: para
    text: 再定義したり、定義済みクラスに定義を
  - kind: para
    text: 追加できる(オープンクラス、モンキーパッチング)
  - kind: para
    text: その代り特定のクラスが複数ファイルに
  - kind: para
    text: 分割されることがないのでわかりやすい
  p43:
  - kind: heading
    level: 1
    text: クロージャ
  - kind: para
    text: <?php
  - kind: para
    text: $h = function($s) {
  - kind: para
    text: return htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
  - kind: para
    text: '};'
  - kind: para
    text: $array = array_map($h, getNames());
  p44:
  - kind: para
    text: PHPの
  - kind: para
    text: 良い言語機能
  p45:
  - kind: heading
    level: 1
    text: array
  - kind: para
    text: <?php
  - kind: para
    text: $old_num = array(1, 2, 3);
  - kind: para
    text: $fruits = ["りんご", "ばなな", "みかん"];
  - kind: para
    text: $tadsan = [
  - kind: para
    text: '"name" => "めぐりねるか",'
  - kind: para
    text: '"age" => 28,'
  - kind: para
    text: '"from" => "北海道",'
  - kind: para
    text: '];'
  p46:
  - kind: heading
    level: 1
    text: foreach
  - kind: para
    text: <?php
  - kind: para
    text: $fruits = ["りんご", "ばなな", "みかん"];
  - kind: para
    text: for ($i = 0; $i < count($fruits); $i++) {
  - kind: para
    text: printf("%s\n", $fruits[$i]);
  - kind: para
    text: '}'
  - kind: para
    text: foreach ($fruits as $fruit) {
  - kind: para
    text: printf("%s\n", $fruit);
  - kind: para
    text: '}'
  p47:
  - kind: heading
    level: 1
    text: ジェネレータ
  - kind: para
    text: <?php
  - kind: para
    text: function fizzbuzz ($to) {
  - kind: para
    text: for ($i = 1; $i <= $to; $i++) {
  - kind: para
    text: $s = "";
  - kind: para
    text: if ($i % 3 == 0) { $s .= "Fizz"; }
  - kind: para
    text: if ($i % 5 == 0) { $s .= "Buzz"; }
  - kind: para
    text: 'yield ($s === "") ? $i : $s;'
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  p48:
  - kind: heading
    level: 1
    text: ジェネレータ + foreach
  - kind: para
    text: // フィボナッチ数列を順に出力する
  - kind: para
    text: foreach (fizzbuzz(100) as $f) {
  - kind: para
    text: echo $f, PHP_EOL;
  - kind: para
    text: '}'
  - kind: para
    text: // これを応用すれば、函数型プログラミングの
  - kind: para
    text: // 遅延リスト(無限リスト)を簡単に実装できる！
  p49:
  - kind: heading
    level: 1
    text: callable (文字列)
  - kind: para
    text: <?php
  - kind: para
    text: $func= "strlen";
  - kind: para
    text: echo $func("abcde"); //=> 5
  - kind: para
    text: $ary = ["a", "bc", "desc", "hello"];
  - kind: para
    text: $bry = array_map("strlen", $ary);
  - kind: para
    text: //=> [1, 2, 3, 4, 5]
  p50:
  - kind: heading
    level: 1
    text: callable (そのほか)
  - kind: para
    text: <?php
  - kind: para
    text: $dt = new DateTime;
  - kind: para
    text: $method = [$dt, "getTimeStamp"];
  - kind: para
    text: echo $method();
  - kind: para
    text: // 1503115455
  - kind: para
    text: echo $dt->getTimeStamp();
  - kind: para
    text: // 1503115455
  p51:
  - kind: heading
    level: 1
    text: Reflection
  - kind: para
    text: <?php
  - kind: para
    text: function sampleFnc($a, $b, $c = null){}
  - kind: para
    text: $ref = new ReflectionFunction("sampleFnc");
  - kind: para
    text: echo $ref->getNumberOfParameters();
  - kind: para
    text: //=> 3
  - kind: para
    text: echo $ref->getNumberOfRequiredParameters();
  - kind: para
    text: //=> 2
  p52:
  - kind: para
    text: Webプログラミン
  - kind: para
    text: グに適した機能
  p53:
  - kind: para
    text: 実はPHPのWebはCGIの世界観
  - kind: para
    text: HTMLを print したりすると
  - kind: para
    text: 出力される
  p54:
  - kind: heading
    level: 1
    text: テンプレート
  - kind: para
    text: <?php
  - kind: para
    text: // HTTPヘッダはボディよりも先に出力する
  - kind: para
    text: 'header("Content-Type: text/plain;");'
  - kind: para
    text: echo "apple\n";
  - kind: para
    text: ?>
  - kind: para
    text: orange
  - kind: para
    text: banana
  - kind: para
    text: <?= getMelon() ?>
  - kind: para
    text: <?php function getMelon(){ return "melon"; }
  p55:
  - kind: para
    text: 実は ?>ほげ<?php は
  - kind: para
    text: echo "ほげ"; と同じ
  p56:
  - kind: heading
    level: 1
    text: テンプレート
  - kind: para
    text: <?php $n = trim(fgets(fopen('php://stdin', 'r')));
  - kind: para
    text: for ($i = 1; $i <= $n; $i++) {
  - kind: para
    text: if ($i % 3 === 0) { ?>Fizz<?php }
  - kind: para
    text: if ($i % 5 === 0) { ?>Buzz<?php }
  - kind: para
    text: elseif ($i % 3 !== 0) echo $i;
  - kind: para
    text: ?>
  - kind: para
    text: <?php }
  p57:
  - kind: heading
    level: 1
    text: 出力バッファリング
  - kind: para
    text: <?php
  - kind: para
    text: ob_start();
  - kind: para
    text: var_dump(new DateTime);
  - kind: para
    text: $str = ob_get_clean();
  - kind: para
    text: var_dump($str);
  p58:
  - kind: heading
    level: 1
    text: $_SERVER
  - kind: para
    text: <?php
  - kind: para
    text: // http://php.net/$_SERVER を読む
  - kind: para
    text: // ユーザーのリクエスト情報
  - kind: para
    text: echo htmlspecialchars($_SERVER['REQUEST_METHOD']);
  - kind: para
    text: echo htmlspecialchars($_SERVER['REQUEST_URI']);
  - kind: para
    text: echo htmlspecialchars($_SERVER['HTTP_ACCEPT_LANGUAGE']);
  p59:
  - kind: heading
    level: 1
    text: HTTPのための機能
  - kind: para
    text: <?php
  - kind: para
    text: $img = base64_decode('R0lGODlhAQABAIABAP///
  - kind: para
    text: wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==');
  - kind: para
    text: http_response_code(404);
  - kind: para
    text: 'header("Content-Type: image/gif");'
  - kind: para
    text: header("Content-Length:".strlen($img));
  - kind: para
    text: echo $img;
  p60:
  - kind: heading
    level: 1
    text: セッション機能
  - kind: para
    text: <?php // logout.php
  - kind: para
    text: session_start();
  - kind: para
    text: $ls_logged_in = isset($_SESSION['user_id']);
  - kind: para
    text: if ($is_logged_in) {
  - kind: para
    text: $_SESSION = [];
  - kind: para
    text: session_regenerate_id();
  - kind: para
    text: '}'
  p61:
  - kind: para
    text: まとめ
  p62:
  - kind: heading
    level: 1
    text: まとめ
  - kind: para
    text: PHPは7.1系(2017年現在安定版)にしよう
  - kind: para
    text: PHPは多様なスタイルがあるよ
  - kind: para
    text: レンタルサーバーとかに適当に置けば
  - kind: para
    text: まあなんとなく動くよ
  - kind: para
    text: PHPはふつうの文法とWeb向きの
  - kind: para
    text: 機能があるプログラミング言語だよ
size:
  max_width: 1024
  max_height: 768
links:
  p29:
  - url: https://qiita.zonu.me/simple-routing
    title: qiita.zonu.me
  p31:
  - url: https://anond.hatelabo.jp/20100427231539
    title: anond.hatelabo.jp
  p58:
  - url: http://php.net/$_SERVER
    title: 'PHP: $_SERVER - Manual'
