size:
  max_width: 1024
  max_height: 768
links:
  p29:
  - url: https://qiita.zonu.me/simple-routing
    title: qiita.zonu.me
  p31:
  - url: https://anond.hatelabo.jp/20100427231539
    title: anond.hatelabo.jp
  p58:
  - url: http://php.net/$_SERVER
    title: 'PHP: $_SERVER - Manual'
