size:
  max_width: 1024
  max_height: 768
links:
  p31:
  - url: php://stderr
    title: stderr
  - url: http://example.com/
    title: Example Domain
text:
  p1:
  - node: p
    children:
    - node: text
      content: 解体新書Composer
    - node: bold
      content: Anatomy of Composer, in Runtime
    - node: text
      content: 'PHPカンファレンス北海道出張版(仮) #phpcondo2017PHPオフ会 '
  p2:
  - node: p
    children:
    - node: text
      content: 'お前誰ようさみけんた (@tadsan) / Zonu.EXE

        '
    - node: text
      content: 'GitHub/Packagistでは id: zonuexe

        •砂川出身、北海道工業大学

        •2012年11月にピクシブ株式会社に入社

        •Emacs Lisper, PHPer

        •入社前は自宅警備をしながらRuby書いてた

        •Qiitaに記事を書いたり変なコメントしてるよ

        •2017年、PHPカンファレンス全部でしゃべった•'
  p4:
  - node: p
    children:
    - node: bold
      content: '         '
    - node: text
      content: Composer使ってますか？
  p5:
  - node: p
    children:
    - node: text
      content: Dependency Manager for PHP
  p6:
  - node: p
    children:
    - node: text
      content: '          使ってないA.          FW経由でB. 直接使ってるC.'
  p7:
  - node: p
    children:
    - node: text
      content: 分かれそう
  p8:
  - node: p
    children:
    - node: text
      content: 本日しない話
  p9:
  - node: p
    children:
    - node: text
      content: PHPのクラスのオートローディングの説明
  p10:
  - node: p
    children:
    - node: text
      content: プロジェクトでのComposerの運用方法
  p11:
  - node: p
    children:
    - node: text
      content: '         過去の発表を読んでください'
  p12:
  - node: p
    children:
    - node: text
      content: https://niconare.nicovideo.jp/watch/kn1371
  p14:
  - node: p
    children:
    - node: text
      content: https://qiita.com/tadsan/items/86099d44d12f1103b0a0
  p15:
  - node: p
    children:
    - node: text
      content: https://qiita.com/tadsan/items/a78c9160418200e2d47a
  p16:
  - node: p
    children:
    - node: text
      content: Composerでできること
  p17:
  - node: p
    children:
    - node: text
      content: ざっくり
  p18:
  - node: p
    children:
    - node: text
      content: '         プロジェクトが         依存するパッケージをダウンロードしてくる'
  p19:
  - node: p
    children:
    - node: text
      content: '         プロジェクトが         依存するパッケージを利用可能にする'
  p20:
  - node: p
    children:
    - node: text
      content: 今日は実行時の話をします
  p21:
  - node: p
    children:
    - node: text
      content: 基本はComposerのautoload.phpを読み込めば準備完了する
  p23:
  - node: p
    children:
    - node: text
      content: 復習
  p24:
  - node: p
    children:
    - node: text
      content: PHPスクリプトの読み込みかた
  p25:
  - node: p
    children:
    - node: text
      content: require, require_once include, include_once
  p26:
  - node: p
    children:
    - node: text
      content: '         場合によるけど基本だいたい同じ'
  p27:
  - node: p
    children:
    - node: text
      content: どこから？
  p28:
  - node: p
    children:
    - node: text
      content: 'ファイルシステムの絶対パス

        A.          include_pathからの相対パスB. プロトコル (ラッパー)C. '
  p29:
  - node: p
    children:
    - node: text
      content: 'ファイルシステムの絶対パスrequire ''/path/to/file.php''; ファイルシステム内のフルパス

        require __DIR__.''/../Klass.php'';          __DIR__マジック定数でスクリプトのディレクトリが入る'
  p30:
  - node: p
    children:
    - node: bold
      content: include_path
    - node: text
      content: 'からの相対パスinclude_pathにディレクトリを追加する

        "."  だいたいデフォルトに が入ってるrequire ''Hoge.php''; require ''Fuga/Piyo.php''; ディレクトリ内も探索される'
  p31:
  - node: p
    children:
    - node: text
      content: 'プロトコル(ラッパー)fopen(''php://stderr'', ''r'') とか         file_get_contents(''http://example.com/'') とかやるための仕組み……が、セキュリティの懸念もあるの         php.ini で、デフォルトでは でallow_url_include = Off になってる'
  p32:
  - node: p
    children:
    - node: text
      content: 改めてComposer
  p33:
  - node: p
    children:
    - node: text
      content: '         オートロード機能ついてる'
  p35:
  - node: p
    children:
    - node: text
      content: '         どうやって読み込んでるの？'
  p36:
  - node: p
    children:
    - node: text
      content: autoload.phpを読もう
  p37:
  - node: p
    children:
    - node: text
      content: 'みなさまの手元のComposer         プロジェクトを見比べながらお聞きください'
  p38:
  - node: p
    children:
    - node: text
      content: '% composer --version Composer version 1.5.2 2017-09-11 16:59:25          % composer install --no-dev --prefer-dist'
  p39:
  - node: p
    children:
    - node: text
      content: 'vendor/autoload.php<?php // autoload.php @generated by Composer          require_once __DIR__ . ''/composer/autoload_real.php''; return ComposerAutoloaderInitbed8ae7d525347237f9cdad08c8930b3::getLoader(); '
  p40:
  - node: p
    children:
    - node: text
      content: 'vendor/autoload.php1.autoload_real.phpを読み込む

        2.謎のクラスの静的メソッドを実行

         たぶん変なバイトキャッシュを         残さないためにcontent-hashが付いたクラス名'
  p42:
  - node: p
    children:
    - node: text
      content: 'autoload_real.php1.$loaderが生成済みなら返すだけ

        2.クラスローダーを読み込むだけのクラスローダーを登録して、使ったらすぐにspl_autoload_unregister する

         なんか環境依存の•ワークアラウンドっぽい気がする'
  p43:
  - node: p
    children:
    - node: text
      content: 'autoload_real.phpif (null !== self::$loader) {     return self::$loader;
        } // Composer\Autoload クラスを読み込むだけのローダー         spl_autoload_register(array(''ComposerAutoloaderInitbedRy'', ''loadClassLoader''),  true,
        true);self::$loader = $loader = new \Composer\Autoload\ClassLoader(); spl_autoload_unregister(array(''ComposerAutoloaderInitbedRy'',
        ''loadClassLoader''));'
  p44:
  - node: p
    children:
    - node: text
      content: 'autoload_real.php1.PHPの実行時環境によってクラス定義の読み込みを変更

        2.autoload_static.php VS 三兄弟

        PHP5.6以上で、HHVMじゃなくて、•zend_loader_file_encoded()が無効ならautoload_staticが利用される'
  p45:
  - node: p
    children:
    - node: text
      content: 'autoload_real.php$useStaticLoader = PHP_VERSION_ID >= 50600 && !defined(''HHVM_VERSION'')
        &&              (!function_exists(''zend_loader_file_encoded'') || !zend_loader_file_encoded());
        if ($useStaticLoader) {     require_once __DIR__ . ''/autoload_static.php'';     call_user_func(\Composer\Autoload\ComposerStaticInitbedRy::getInitializer($loader));
        } else {     $map = require __DIR__ . ''/autoload_namespaces.php'';     foreach
        ($map as $namespace => $path) {         $loader->set($namespace, $path);     }     $map
        = require __DIR__ . ''/autoload_psr4.php'';     foreach ($map as $namespace
        => $path) {         $loader->setPsr4($namespace, $path);     }     $classMap
        = require __DIR__ . ''/autoload_classmap.php'';     if ($classMap) {         $loader->addClassMap($classMap);     }
        }'
  p46:
  - node: p
    children:
    - node: text
      content: 'autoload_static.php         プロジェクトの依存パッケージと、composer installのオプションに依存

         デフォルトではComposer.jsonの定義通りのローディングを生成

         --optimize-autoloader オプションでクラスマップを強制で生成する'
  p47:
  - node: p
    children:
    - node: text
      content: autoload_static.php (PSR-4のみ)<?php // autoload_static.php @generated
        by Composer namespace Composer\Autoload; class ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3
        {     public static $prefixLengthsPsr4 = array (         'T' =>          array
        (             'Teto\\' => 5,         ),     );     public static $prefixDirsPsr4
        = array (         'Teto\\' =>          array (             0 => __DIR__ .
        '/../..' . '/src',         ),     );     public static function getInitializer(ClassLoader
        $loader) {         return \Closure::bind(function () use ($loader) {             $loader->prefixLengthsPsr4
        = ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3::$prefixLengthsPsr4;             $loader->prefixDirsPsr4
        = ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3::$prefixDirsPsr4;         },
        null, ClassLoader::class);     } }
  p48:
  - node: p
    children:
    - node: text
      content: autoload_static.php (optimized)    public static $classMap = array
        (         'Teto\\Object\\Helper' => __DIR__ . '/../..' . '/src/Object/Helper.php',         'Teto\\Object\\MethodAlias'
        => __DIR__ . '/../..' . '/src/Object/MethodAlias.php',         'Teto\\Object\\ObjectArray'
        => __DIR__ . '/../..' . '/src/Object/ObjectArray.php',         'Teto\\Object\\PrivateGetter'
        => __DIR__ . '/../..' . '/src/Object/PrivateGetter.php',         'Teto\\Object\\PrivateStrictGetter'
        => __DIR__ . '/../..' . '/src/Object/PrivateStrictGetter.php',         'Teto\\Object\\PropertyLikeMethod'
        => __DIR__ . '/../..' . '/src/Object/PropertyLikeMethod.php',         'Teto\\Object\\ReadOnly'
        => __DIR__ . '/../..' . '/src/Object/ReadOnly.php',         'Teto\\Object\\ToArrayInterface'
        => __DIR__ . '/../..' . '/src/Object/ToArrayInterface.php',         'Teto\\Object\\TypeAssert'
        => __DIR__ . '/../..' . '/src/Object/TypeAssert.php',         'Teto\\Object\\TypeDefinition'
        => __DIR__ . '/../..' . '/src/Object/TypeDefinition.php',         'Teto\\Object\\TypedProperty'
        => __DIR__ . '/../..' . '/src/Object/TypedProperty.php',     );
  p49:
  - node: p
    children:
    - node: text
      content: 'autoload_static.phpの大事なとこClosure::bind()でスコープ束縛して、         メソッド呼び出しをけちりながらprivateメンバーにセットしてるreturn \Closure::bind(function () use ($loader)
        {     $loader->prefixLengthsPsr4 = ComposerStaticInitbedRy::$prefixLengthsPsr4;     $loader->prefixDirsPsr4
        = ComposerStaticInitbedRy::$prefixDirsPsr4;     $loader->classMap = ComposerStaticInitbedRy::$classMap;
        }, null, ClassLoader::class);'
  p50:
  - node: p
    children:
    - node: text
      content: 'ClassLoader.phpクラスローダーの実装本体

        いままで設定された情報をもとにクラス名の解決・ファイルロードをする

        動的に変動する部分は分離されてるので、         バイトコードがキャッシュされても特に問題なさそうに作ってるっぽい'
  p51:
  - node: p
    children:
    - node: text
      content: 'ClassLoader.phpspl_autoload_register()で呼ばれる

        クラスマップにあったらそれを読む

        なかったらpsr-4, psr-2を読む

        PEARに依存するなどの場合はinclude_pathを読む'
  p52:
  - node: p
    children:
    - node: text
      content: これによって得られる知見
  p53:
  - node: p
    children:
    - node: text
      content: Composerは、いろんなPHPのバージョンとか実行環境で動くように書かれてる
  p54:
  - node: p
    children:
    - node: text
      content: 実行時にcomposer.jsonとかcomposer.lockは使ってなくて、静的なPHPスクリプトファイルが書き出される
  p55:
  - node: p
    children:
    - node: text
      content: composer installサーバーでの必要はなく、手元でインストールしてvendorディレクトリごと転送してやればいい
  p56:
  - node: p
    children:
    - node: text
      content: よくある誤解
  p57:
  - node: p
    children:
    - node: text
      content: 「レンタルサーバーの最安プランでPHP動かしてるからComposer入らないんだ…」といったことはない
  p58:
  - node: p
    children:
    - node: bold
      content: '         '
    - node: text
      content: 本筋から外れた話
  p59:
  - node: p
    children:
    - node: text
      content: 'Autoloader Optimization

        https://getcomposer.org/doc/articles/autoloader-optimization.md'
  p60:
  - node: p
    children:
    - node: text
      content: '         Level 1         本番運用時はが基本--optimize-autoloader'
  p61:
  - node: p
    children:
    - node: text
      content: '         ……そのほかは         効果あるのかな？(私は使ってないです)'
  p62:
  - node: p
    children:
    - node: text
      content: 予告
  p63:
  - node: p
    children:
    - node: text
      content: PHP AdventCalendar 2017ではComposerとか全然考慮されてない(zipで配布されてる)SDKをむりやりComposerで管理する話を書きます
