text:
  p1:
  - kind: heading
    level: 1
    text: Composer解体新書
  - kind: para
    text: Anatomy of Composer, in Runtime
  - kind: para
    text: PHPカンファレンス北海道出張版(仮)
  - kind: para
    text: 'PHPオフ会 #phpcondo2017'
  p2:
  - kind: heading
    level: 1
    text: お前誰よ
  - kind: list
    items:
    - うさみけんた (@tadsan) / Zonu.EXE
    - 'GitHub/Packagistでは id: zonuexe'
    - 砂川出身、北海道工業大学
    - 2012年11月にピクシブ株式会社に入社
    - Emacs Lisper, PHPer
    - 入社前は自宅警備をしながらRuby書いてた
    - Qiitaに記事を書いたり変なコメントしてるよ
    - 2017年、PHPカンファレンス全部でしゃべった
  p3: []
  p4:
  - kind: para
    text: Composer
  - kind: para
    text: 使ってますか？
  p5:
  - kind: para
    text: Dependency Manager for PHP
  p6:
  - kind: para
    text: A. 使ってない
  - kind: para
    text: B. FW経由で
  - kind: para
    text: C. 直接使ってる
  p7:
  - kind: para
    text: 分かれそう
  p8:
  - kind: para
    text: 本日しない話
  p9:
  - kind: para
    text: PHPのクラスのオート
  - kind: para
    text: ローディングの説明
  p10:
  - kind: para
    text: プロジェクトでの
  - kind: para
    text: Composerの運用方法
  p11:
  - kind: para
    text: 過去の発表を
  - kind: para
    text: 読んでください
  p12:
  - kind: para
    text: https://niconare.nicovideo.jp/watch/kn1371
  p13: []
  p14:
  - kind: para
    text: https://qiita.com/tadsan/items/86099d44d12f1103b0a0
  p15:
  - kind: para
    text: https://qiita.com/tadsan/items/a78c9160418200e2d47a
  p16:
  - kind: para
    text: Composerで
  - kind: para
    text: できること
  p17:
  - kind: para
    text: ざっくり
  p18:
  - kind: para
    text: プロジェクトが
  - kind: para
    text: 依存するパッケージを
  - kind: para
    text: ダウンロードしてくる
  p19:
  - kind: para
    text: プロジェクトが
  - kind: para
    text: 依存するパッケージを
  - kind: para
    text: 利用可能にする
  p20:
  - kind: para
    text: 今日は実行時の
  - kind: para
    text: 話をします
  p21:
  - kind: para
    text: 基本はComposerの
  - kind: para
    text: autoload.phpを読み込
  - kind: para
    text: めば準備完了する
  p22: []
  p23:
  - kind: para
    text: 復習
  p24:
  - kind: para
    text: PHPスクリプト
  - kind: para
    text: の読み込みかた
  p25:
  - kind: para
    text: require, require_once
  - kind: para
    text: include, include_once
  p26:
  - kind: para
    text: 場合によるけど
  - kind: para
    text: 基本だいたい同じ
  p27:
  - kind: para
    text: どこから？
  p28:
  - kind: para
    text: A. ファイルシステムの絶対パス
  - kind: para
    text: B. include_pathからの相対パス
  - kind: para
    text: C. プロトコル (ラッパー)
  p29:
  - kind: heading
    level: 1
    text: ファイルシステムの絶対パス
  - kind: para
    text: require '/path/to/file.php';
  - kind: para
    text: ファイルシステム内のフルパス
  - kind: para
    text: require __DIR__.'/../Klass.php';
  - kind: para
    text: マジック定数__DIR__で
  - kind: para
    text: スクリプトのディレクトリが入る
  p30:
  - kind: para
    text: include_pathからの相対パス
  - kind: para
    text: include_pathにディレクトリを追加する
  - kind: para
    text: だいたいデフォルトに "." が入ってる
  - kind: para
    text: require 'Hoge.php';
  - kind: para
    text: require 'Fuga/Piyo.php';
  - kind: para
    text: ディレクトリ内も探索される
  p31:
  - kind: heading
    level: 1
    text: プロトコル(ラッパー)
  - kind: para
    text: fopen('php://stderr', 'r') とか
  - kind: para
    text: file_get_contents('http://example.com/')
  - kind: para
    text: とかやるための仕組み
  - kind: para
    text: ……が、セキュリティの懸念もあるの
  - kind: para
    text: で、デフォルトでは php.ini で
  - kind: para
    text: allow_url_include = Off になってる
  p32:
  - kind: para
    text: 改めて
  - kind: para
    text: Composer
  p33:
  - kind: para
    text: オートロード
  - kind: para
    text: 機能ついてる
  p34: []
  p35:
  - kind: para
    text: どうやって
  - kind: para
    text: 読み込んでるの？
  p36:
  - kind: para
    text: autoload.phpを
  - kind: para
    text: 読もう
  p37:
  - kind: para
    text: みなさまの手元のComposer
  - kind: para
    text: プロジェクトを
  - kind: para
    text: 見比べながらお聞きください
  p38:
  - kind: para
    text: '% composer --version'
  - kind: para
    text: Composer version 1.5.2 2017-09-11 16:59:25
  - kind: para
    text: '% composer install --no-dev --prefer-dist'
  p39:
  - kind: heading
    level: 1
    text: vendor/autoload.php
  - kind: para
    text: <?php
  - kind: para
    text: // autoload.php @generated by Composer
  - kind: para
    text: require_once __DIR__ . '/composer/autoload_real.php';
  - kind: para
    text: return
  - kind: para
    text: ComposerAutoloaderInitbed8ae7d525347237f9cdad08c8930b3::getLoader();
  p40:
  - kind: heading
    level: 1
    text: vendor/autoload.php
  - kind: para
    text: 1.autoload_real.phpを読み込む
  - kind: para
    text: 2.謎のクラスの静的メソッドを実行
  - kind: para
    text: たぶん変なバイトキャッシュを
  - kind: para
    text: 残さないためにcontent-hashが付いた
  - kind: para
    text: クラス名
  p41: []
  p42:
  - kind: heading
    level: 1
    text: autoload_real.php
  - kind: para
    text: 1.$loaderが生成済みなら返すだけ
  - kind: para
    text: 2.クラスローダーを読み込むだけのクラス
  - kind: para
    text: ローダーを登録して、使ったらすぐに
  - kind: para
    text: spl_autoload_unregister する
  - kind: list
    items:
    - なんか環境依存の
  - kind: para
    text: ワークアラウンドっぽい気がする
  p43:
  - kind: heading
    level: 1
    text: autoload_real.php
  - kind: para
    text: if (null !== self::$loader) {
  - kind: para
    text: return self::$loader;
  - kind: para
    text: '}'
  - kind: para
    text: // Composer\Autoload クラスを読み込むだけのローダー
  - kind: para
    text: spl_autoload_register(array('ComposerAutoloaderInitbedRy', 'loadClassLoader'),
  - kind: para
    text: true, true);
  - kind: para
    text: self::$loader = $loader = new \Composer\Autoload\ClassLoader();
  - kind: para
    text: spl_autoload_unregister(array('ComposerAutoloaderInitbedRy', 'loadClassLoader'));
  p44:
  - kind: heading
    level: 1
    text: autoload_real.php
  - kind: para
    text: 1.PHPの実行時環境によってクラス定義の
  - kind: para
    text: 読み込みを変更
  - kind: para
    text: 2.autoload_static.php VS 三兄弟
  - kind: list
    items:
    - PHP5.6以上で、HHVMじゃなくて、
  - kind: para
    text: zend_loader_file_encoded()が無効なら
  - kind: para
    text: autoload_staticが利用される
  p45:
  - kind: heading
    level: 1
    text: autoload_real.php
  - kind: para
    text: $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') &&
  - kind: para
    text: (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
  - kind: para
    text: if ($useStaticLoader) {
  - kind: para
    text: require_once __DIR__ . '/autoload_static.php';
  - kind: para
    text: call_user_func(\Composer\Autoload\ComposerStaticInitbedRy::getInitializer($loader));
  - kind: para
    text: '} else {'
  - kind: para
    text: $map = require __DIR__ . '/autoload_namespaces.php';
  - kind: para
    text: foreach ($map as $namespace => $path) {
  - kind: para
    text: $loader->set($namespace, $path);
  - kind: para
    text: '}'
  - kind: para
    text: $map = require __DIR__ . '/autoload_psr4.php';
  - kind: para
    text: foreach ($map as $namespace => $path) {
  - kind: para
    text: $loader->setPsr4($namespace, $path);
  - kind: para
    text: '}'
  - kind: para
    text: $classMap = require __DIR__ . '/autoload_classmap.php';
  - kind: para
    text: if ($classMap) {
  - kind: para
    text: $loader->addClassMap($classMap);
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  p46:
  - kind: heading
    level: 1
    text: autoload_static.php
  - kind: para
    text: プロジェクトの依存パッケージと、
  - kind: para
    text: composer installのオプションに依存
  - kind: para
    text: デフォルトではComposer.jsonの
  - kind: para
    text: 定義通りのローディングを生成
  - kind: para
    text: --optimize-autoloader オプションで
  - kind: para
    text: クラスマップを強制で生成する
  p47:
  - kind: heading
    level: 1
    text: autoload_static.php (PSR-4のみ)
  - kind: para
    text: <?php // autoload_static.php @generated by Composer
  - kind: para
    text: namespace Composer\Autoload;
  - kind: para
    text: class ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3 {
  - kind: para
    text: public static $prefixLengthsPsr4 = array (
  - kind: para
    text: '''T'' =>'
  - kind: para
    text: array (
  - kind: para
    text: '''Teto\\'' => 5,'
  - kind: para
    text: ),
  - kind: para
    text: );
  - kind: para
    text: public static $prefixDirsPsr4 = array (
  - kind: para
    text: '''Teto\\'' =>'
  - kind: para
    text: array (
  - kind: para
    text: 0 => __DIR__ . '/../..' . '/src',
  - kind: para
    text: ),
  - kind: para
    text: );
  - kind: para
    text: public static function getInitializer(ClassLoader $loader) {
  - kind: para
    text: return \Closure::bind(function () use ($loader) {
  - kind: para
    text: $loader->prefixLengthsPsr4 = ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3::$prefixLengthsPsr4;
  - kind: para
    text: $loader->prefixDirsPsr4 = ComposerStaticInitbed8ae7d525347237f9cdad08c8930b3::$prefixDirsPsr4;
  - kind: para
    text: '}, null, ClassLoader::class);'
  - kind: para
    text: '}'
  - kind: para
    text: '}'
  p48:
  - kind: heading
    level: 1
    text: autoload_static.php (optimized)
  - kind: para
    text: public static $classMap = array (
  - kind: para
    text: '''Teto\\Object\\Helper'' => __DIR__ . ''/../..'' . ''/src/Object/Helper.php'','
  - kind: para
    text: '''Teto\\Object\\MethodAlias'' => __DIR__ . ''/../..'' . ''/src/Object/MethodAlias.php'','
  - kind: para
    text: '''Teto\\Object\\ObjectArray'' => __DIR__ . ''/../..'' . ''/src/Object/ObjectArray.php'','
  - kind: para
    text: '''Teto\\Object\\PrivateGetter'' => __DIR__ . ''/../..'' . ''/src/Object/PrivateGetter.php'','
  - kind: para
    text: '''Teto\\Object\\PrivateStrictGetter'' => __DIR__ . ''/../..'' . ''/src/Object/'
  - kind: para
    text: PrivateStrictGetter.php',
  - kind: para
    text: '''Teto\\Object\\PropertyLikeMethod'' => __DIR__ . ''/../..'' . ''/src/Object/'
  - kind: para
    text: PropertyLikeMethod.php',
  - kind: para
    text: '''Teto\\Object\\ReadOnly'' => __DIR__ . ''/../..'' . ''/src/Object/ReadOnly.php'','
  - kind: para
    text: '''Teto\\Object\\ToArrayInterface'' => __DIR__ . ''/../..'' . ''/src/Object/'
  - kind: para
    text: ToArrayInterface.php',
  - kind: para
    text: '''Teto\\Object\\TypeAssert'' => __DIR__ . ''/../..'' . ''/src/Object/TypeAssert.php'','
  - kind: para
    text: '''Teto\\Object\\TypeDefinition'' => __DIR__ . ''/../..'' . ''/src/Object/'
  - kind: para
    text: TypeDefinition.php',
  - kind: para
    text: '''Teto\\Object\\TypedProperty'' => __DIR__ . ''/../..'' . ''/src/Object/TypedProperty.php'','
  - kind: para
    text: );
  p49:
  - kind: heading
    level: 1
    text: autoload_static.phpの大事なとこ
  - kind: heading
    level: 2
    text: Closure::bind()でスコープ束縛して、
  - kind: heading
    level: 2
    text: メソッド呼び出しをけちりながら
  - kind: heading
    level: 2
    text: privateメンバーにセットしてる
  - kind: para
    text: return \Closure::bind(function () use ($loader) {
  - kind: para
    text: $loader->prefixLengthsPsr4 = ComposerStaticInitbedRy::$prefixLengthsPsr4;
  - kind: para
    text: $loader->prefixDirsPsr4 = ComposerStaticInitbedRy::$prefixDirsPsr4;
  - kind: para
    text: $loader->classMap = ComposerStaticInitbedRy::$classMap;
  - kind: para
    text: '}, null, ClassLoader::class);'
  p50:
  - kind: heading
    level: 1
    text: ClassLoader.php
  - kind: para
    text: クラスローダーの実装本体
  - kind: para
    text: いままで設定された情報をもとにクラス
  - kind: para
    text: 名の解決・ファイルロードをする
  - kind: para
    text: 動的に変動する部分は分離されてるので、
  - kind: para
    text: バイトコードがキャッシュされても
  - kind: para
    text: 特に問題なさそうに作ってるっぽい
  p51:
  - kind: heading
    level: 1
    text: ClassLoader.php
  - kind: para
    text: spl_autoload_register()で呼ばれる
  - kind: para
    text: クラスマップにあったらそれを読む
  - kind: para
    text: なかったらpsr-4, psr-2を読む
  - kind: para
    text: PEARに依存するなどの場合は
  - kind: para
    text: include_pathを読む
  p52:
  - kind: para
    text: これによって
  - kind: para
    text: 得られる知見
  p53:
  - kind: para
    text: Composerは、いろんなPHP
  - kind: para
    text: のバージョンとか実行環境
  - kind: para
    text: で動くように書かれてる
  p54:
  - kind: para
    text: 実行時にcomposer.jsonとか
  - kind: para
    text: composer.lockは使ってなく
  - kind: para
    text: て、静的なPHPスクリプト
  - kind: para
    text: ファイルが書き出される
  p55:
  - kind: para
    text: サーバーでcomposer install
  - kind: para
    text: の必要はなく、手元でインス
  - kind: para
    text: トールしてvendorディレクト
  - kind: para
    text: リごと転送してやればいい
  p56:
  - kind: para
    text: よくある誤解
  p57:
  - kind: para
    text: 「レンタルサーバーの最安プ
  - kind: para
    text: ランでPHP動かしてるから
  - kind: para
    text: Composer入らないんだ…」
  - kind: para
    text: といったことはない
  p58:
  - kind: para
    text: 本筋から
  - kind: para
    text: 外れた話
  p59:
  - kind: para
    text: Autoloader
  - kind: para
    text: Optimization
  - kind: para
    text: https://getcomposer.org/doc/articles/autoloader-optimization.md
  p60:
  - kind: para
    text: Level 1
  - kind: para
    text: 本番運用時は
  - kind: para
    text: --optimize-autoloaderが基本
  p61:
  - kind: para
    text: ……そのほかは
  - kind: para
    text: 効果あるのかな？
  - kind: para
    text: (私は使ってないです)
  p62:
  - kind: para
    text: 予告
  p63:
  - kind: para
    text: PHP AdventCalendar 2017では
  - kind: para
    text: Composerとか全然考慮されてない
  - kind: para
    text: (zipで配布されてる)SDKをむりやり
  - kind: para
    text: Composerで管理する話を書きます
size:
  max_width: 1024
  max_height: 768
links:
  p31:
  - url: php://stderr
    title: stderr
  - url: http://example.com/
    title: Example Domain
