title: 仕事で使えるComposer
date: '2016-04-16'
stem: kn1371_20160416_composer-for-work
download: kn1371_20160416_仕事で使えるComposer.pdf
hashtags:
  - phpcondo
events:
  - name: PHPカンファレンス北海道2016
    url: https://web.archive.org/web/20161024061838/http://phpcon.sapporo-php.net/2016/
    location: 札幌市白石区
    place: 札幌市産業振興センター
    type: レギュラーセッション
    talk_duration: 20
    presented_at: '2025-08-27'
tags:
  - lang:PHP
  - Composer
