title: プログラミング環境としてのPHP
date: '2017-08-19'
stem: kn2529_20170819_php-as-a-programming-environment
download: 'kn2529_20170819_プログラミング環境としてのPHP #opendevcon.pdf'
hashtags:
  - opendevcon
events:
  - name: Open Developers Conference 2017 Tokyo
    url: https://www.ospn.jp/odc2017/
    location: 東京都大田区
    place: 日本工学院専門学校 蒲田キャンパス
    presented_at: '2017-08-19'
    type: 出張版 PHP勉強会＠東京
    talk_duration: 15
tags:
  - lang:PHP
  - ODC
