title: Composer解体新書 (実行時篇)
date: '2017-12-01'
stem: kn2785_20171201_composer-runtime-under-the-hood
download: 'kn2785_20171201_Composer解体新書 (実行時篇) #phpcondo2017.pdf'
hashtags:
  - phpcondo2017
events:
  - name: PHPカンファレンス北海道出張版(仮) PHPオフ会
    url: https://phpcondo.connpass.com/event/69958/
    location: 札幌市中央区
    place: 株式会社インフィニットループ
    presented_at: '2017-11-25'
    type: レギュラーセッション
    talk_duration: 30
