title: PSRで学ぶHTTP Webアプリケーションの実践
date: '2020-12-12'
download: 20201212_psr-http-web-application-practice.pdf
hashtags:
  - phpcon
events:
  - name: PHPカンファレンス2020
    url: https://phpcon.php.gr.jp/2020/
    location: オンライン
    place: YouTube Live
    presented_at: '2020-12-12'
    type: Long session
    talk_duration: 60
tags:
  - lang:PHP
  - PSR
  - フレームワーク
